### ISSUE TITLE
big artifacts to the side of my second monitor

### ISSUE THREAD

**Issue by Vaashx** [TheG-VAN/dwm_frame_interpolator#3]
big artifacts to the side of my second monitor, when activated for gaming, the artifacts shows when doing fast motion or even simple in the game, it's as if the interpolation exceeds the main screen, btw i'm on a ultrawide monitor 2560x1080 / 21:9 / 160 Hz

**Comment by TheG-VAN** [comment]
I don't currently have a second monitor so I'm not able to test this out to fix it. I am planning on getting another monitor soon so I will try and fix this then.

**Comment by Vaashx** [comment]
> I don't currently have a second monitor so I'm not able to test this out to fix it. I am planning on getting another monitor soon so I will try and fix this then.

sure no worries thx for the answers
