### ISSUE TITLE
need a fixed for people with multiple monitor

### ISSUE THREAD

**Issue by Vaashx** [TheG-VAN/dwm_frame_interpolator#5]
Hi G-Van!, it's me again ^^, first i'm really suprise and really glad i've found your software it really good i'm speechless about it, it's really ipressive how good the smoothness is, but i really need your help since when i have my second monitor on, when i try using DWM-i, i have literrally big artifact everywhere on my main screen and my second screen, it's not playable, i can't even see my screen/game cuz of artifacts, so my question and i really hope that you can do this on your app, Can you make the app only focusing on the main screen ? it would be so good to have that, really dude, i'm in love with the smootheness that your app provide for me even lossless scaling or afmf2 does provide me this and lossless is pretty good, i beg you if you can do that. thx for all !!!

**Comment by TheG-VAN** [comment]
Thank you for the compliments. I can hook my pc to my tv as well as my monitor as a makeshift dual monitor display to try and work out a fix. I'll have a go over the weekend and hopefully I will come up with something.

**Comment by Vaashx** [comment]
> Thank you for the compliments. I can hook my pc to my tv as well as my monitor as a makeshift dual monitor display to try and work out a fix. I'll have a go over the weekend and hopefully I will come up with something.
thank you dude really hope it goes well !, take care.

**Comment by TheG-VAN** [comment]
Hi, I had a go at making it work for dual monitors. The latest release is here: https://github.com/TheG-VAN/dwm_frame_interpolator/releases/tag/v0.0.15

Let me know if there are any issues

**Comment by Vaashx** [comment]
> Hi, I had a go at making it work for dual monitors. The latest release is here: https://github.com/TheG-VAN/dwm_frame_interpolator/releases/tag/v0.0.15
> 
> Let me know if there are any issues

work pretty well, nice work thx dude.
